// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dist2
NumericMatrix dist2(NumericMatrix x1, NumericMatrix x2);
RcppExport SEXP gwxtab_dist2(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x2(x2SEXP);
    __result = Rcpp::wrap(dist2(x1, x2));
    return __result;
END_RCPP
}
// bisq2
NumericMatrix bisq2(NumericMatrix x1, NumericMatrix x2, double h);
RcppExport SEXP gwxtab_bisq2(SEXP x1SEXP, SEXP x2SEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(bisq2(x1, x2, h));
    return __result;
END_RCPP
}
// bisq2ad
NumericMatrix bisq2ad(NumericMatrix x1, NumericMatrix x2, NumericVector h);
RcppExport SEXP gwxtab_bisq2ad(SEXP x1SEXP, SEXP x2SEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    __result = Rcpp::wrap(bisq2ad(x1, x2, h));
    return __result;
END_RCPP
}
// bisq
NumericVector bisq(NumericMatrix x1, NumericVector x2, double h);
RcppExport SEXP gwxtab_bisq(SEXP x1SEXP, SEXP x2SEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(bisq(x1, x2, h));
    return __result;
END_RCPP
}
// gcdist2
NumericMatrix gcdist2(NumericMatrix x1, NumericMatrix x2);
RcppExport SEXP gwxtab_gcdist2(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x2(x2SEXP);
    __result = Rcpp::wrap(gcdist2(x1, x2));
    return __result;
END_RCPP
}
