# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist2 <- function(x1, x2) {
    .Call('gwxtab_dist2', PACKAGE = 'gwxtab', x1, x2)
}

bisq2 <- function(x1, x2, h) {
    .Call('gwxtab_bisq2', PACKAGE = 'gwxtab', x1, x2, h)
}

bisq2ad <- function(x1, x2, h) {
    .Call('gwxtab_bisq2ad', PACKAGE = 'gwxtab', x1, x2, h)
}

bisq <- function(x1, x2, h) {
    .Call('gwxtab_bisq', PACKAGE = 'gwxtab', x1, x2, h)
}

gcdist2 <- function(x1, x2) {
    .Call('gwxtab_gcdist2', PACKAGE = 'gwxtab', x1, x2)
}

